/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_turbineyan_devicedelegate_UartJniHelper */

#ifndef _Included_com_turbineyan_devicedelegate_UartJniHelper
#define _Included_com_turbineyan_devicedelegate_UartJniHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_turbineyan_devicedelegate_UartJniHelper
 * Method:    devOpen
 * Signature: (Ljava/lang/String;II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_turbineyan_devicedelegate_UartJniHelper_devOpen
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_turbineyan_devicedelegate_UartJniHelper
 * Method:    devClose
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_turbineyan_devicedelegate_UartJniHelper_devClose
  (JNIEnv *, jclass);

/*
 * Class:     com_turbineyan_devicedelegate_UartJniHelper
 * Method:    send
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_turbineyan_devicedelegate_UartJniHelper_send
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_turbineyan_devicedelegate_UartJniHelper
 * Method:    recv
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_turbineyan_devicedelegate_UartJniHelper_recv
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_turbineyan_devicedelegate_UartJniHelper
 * Method:    lastError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_turbineyan_devicedelegate_UartJniHelper_lastError
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
